apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-platform
  template:
    metadata:
      labels:
        app: cicd-platform
    spec:
      containers:
        - name: cicd-platform
          image: ghcr.io/ananyapraneet/cicd-platform:bc39a26c72ff65df28808955ca5c9b4d6c5a7f9a
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
